/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xx.h"
#include "stm32f401xx_gpio_driver.h"

//set delay
void delay(void)
{
	for(uint32_t i=0; i< 200000; i++);
}

int main(void)
{
	GPIO_Handle_t GpioLed, GpioBtn, LED1, LED2;

	//Enable GPIO Clocks
	GPIO_PeriClockControl(GPIOA, ENABLE);
	GPIO_PeriClockControl(GPIOB, ENABLE);

	//Onboard LED
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	GPIO_Init(&GpioLed);

	//Button (PC13)

	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&GpioBtn);

	//External LED1 (PA6)

	LED1.pGPIOx = GPIOA;
	LED1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	LED1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	LED1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&LED1);

	//External LED2 (PA7)

	LED2.pGPIOx = GPIOA;
	LED2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
	LED2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	LED2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	LED2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	LED2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	GPIO_Init(&LED2);

	uint8_t led_state = 0;

	while(1)
	{
		//task 1
		if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0) //IF BUTTON PRESSED
		{
			delay();

			if(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0)
			{
				led_state = !led_state;
				GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_5, led_state);

				//wait until button released
				while(GPIO_ReadFromInputPin(GPIOC, GPIO_PIN_NO_13) == 0);
			}
		}

		//Task 2 :Alternating LEDs
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, 1);
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, 0);
		delay();

		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_6, 0);
		GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, 1);
		delay();
	}

}





#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


